SELECT ALL 
F.ISS_AIRLINE,
F.DOC_NO,
F.COUPON_NO,
F.FLIGHT_NO,
F.DATE_OF_ISSUE,
F.UPLIFT_DATE AS FLT_DATE,
TO_CHAR(F.UPLIFT_DATE, 'MM') FLT_MONTH,
TO_CHAR(F.UPLIFT_DATE, 'yyyy') FLT_YEAR,
F.AOS,
M.SALES_SOURCE,
F.FROM_CITY||F.TO_CITY Sector,
DECODE(UPC.COUNTRY_CODE, TOC.COUNTRY_CODE, 'D', 'I') AS Rtyp,
SUM(DECODE(F.PAX_TYPE, 'A', 1, 0)*NVL(F.PAX_COUNT, 0)) adl,
SUM(DECODE(F.PAX_TYPE, 'C', 1, 0)*NVL(F.PAX_COUNT, 0)) chd,
SUM(DECODE(F.PAX_TYPE, 'I', 1, 0)*NVL(F.PAX_COUNT, 0)) Inf,
SUM(NVL(F.PAX_COUNT, 0)) Pax_cnt,
SUM(DECODE(F.NON_REV_FLAG, 'Y', 1, 0)*NVL(F.PAX_COUNT, 0)) Foc,
COUNT(F.DOC_NO) CPNS_COUNT,
F.DOC_CLASS, DECODE(F.CLASS, NULL,'  ', 'F', 'F', 'C', 'C', 'D', 'C', 'J', 'C', 'I', 'I', 'Y') SERVICE_CLASS,
F.PAX_TYPE, DECODE(F.ISS_AIRLINE, 738, F.AUDIT_PRORATE_CURRENCY, F.PRORATE_CURRENCY) curr,
SUM(DECODE(F.ISS_AIRLINE, 738, F.AUDIT_SECTOR_AMOUNT_SC, F.SECTOR_VALUE)) "REVENUE-NTE",
CASE
    WHEN (DECODE(UPC.COUNTRY_CODE, TOC.COUNTRY_CODE, 'D', 'I') = 'I' AND DECODE(F.ISS_AIRLINE, 738, F.AUDIT_PRORATE_CURRENCY, F.PRORATE_CURRENCY) = 'VND')
    THEN 'USD'
    ELSE DECODE(F.ISS_AIRLINE, 738, F.AUDIT_PRORATE_CURRENCY, F.PRORATE_CURRENCY)
END AS EQUIV_CURR,
CASE 
    WHEN (DECODE(UPC.COUNTRY_CODE, TOC.COUNTRY_CODE, 'D', 'I') = 'I' AND DECODE(F.ISS_AIRLINE, 738, F.AUDIT_PRORATE_CURRENCY, F.PRORATE_CURRENCY) = 'VND')
    THEN INTERNAL_CURR_CONV('VND','USD',F.DATE_OF_ISSUE,SUM(DECODE(F.ISS_AIRLINE, 738, F.AUDIT_SECTOR_AMOUNT_SC, F.SECTOR_VALUE)))
    ELSE SUM(DECODE(F.ISS_AIRLINE, 738, F.AUDIT_SECTOR_AMOUNT_SC, F.SECTOR_VALUE))
END AS EQUIV_REV_NTE,                                
SUM(
DECODE (F.ISS_AIRLINE,
                                    '738', 
                                     DECODE (NVL (F.MATCHED_FLAG,'N'),'N',F.REVENUE, INTERNAL_CURR_CONV(NVL(F.AUDIT_PRORATE_CURRENCY,F.PRORATE_CURRENCY),'VND',NVL(F.DATE_OF_ISSUE,F.ORIG_DATE_OF_ISSUE),1)*F.AUDIT_SECTOR_AMOUNT_SC
                                                                ),
                                     F.REVENUE)) "REVENUE-VND",
UPC.COUNTRY_CODE ORI_COUNTRY,
TOC.COUNTRY_CODE DES_COUNTRY,
CASE
    WHEN F.FLIGHT_NO <8000 THEN 'VN'
    WHEN F.FLIGHT_NO >8999 THEN 'VN'
    ELSE '0V'
END AS CARRIER
FROM
CITY_MASTER UPC,
CITY_MASTER TOC,
REVERA_OWNER.EFF_REP_TABLE F
LEFT JOIN TICKET_MAIN M
ON ( F.ISS_AIRLINE = M.ISS_AIRLINE
AND F.DOC_NO = M.DOC_NO
)
WHERE
F.UPLIFT_DATE BETWEEN '01-JAN-2020' AND '07-JAN-2020'
AND  ((F.UPLIFT_STATION=UPC.CITY_CODE_ALPHA)
AND (F.TO_CITY=TOC.CITY_CODE_ALPHA))
AND F.FLIGHT_NO NOT BETWEEN  9000  AND  9999
AND ROWNUM <=10
GROUP BY
F.ISS_AIRLINE,
F.DOC_NO,
F.COUPON_NO,
F.FLIGHT_NO,
F.DATE_OF_ISSUE,
F.UPLIFT_DATE,
TO_CHAR(F.UPLIFT_DATE, 'MM'),
TO_CHAR(F.UPLIFT_DATE, 'yyyy'),
F.AOS,
M.SALES_SOURCE,
F.FROM_CITY||F.TO_CITY,
DECODE(UPC.COUNTRY_CODE, TOC.COUNTRY_CODE, 'D', 'I'), 
F.DOC_CLASS,
DECODE(F.CLASS, NULL,'  ', 'F', 'F', 'C', 'C', 'D', 'C', 'J', 'C', 'I', 'I', 'Y'),
F.PAX_TYPE, 
DECODE(F.ISS_AIRLINE, 738, F.AUDIT_PRORATE_CURRENCY, F.PRORATE_CURRENCY),
UPC.COUNTRY_CODE, 
TOC.COUNTRY_CODE,
--DECODE(F.DOC_CLASS,'MCO', DECODE(SUBSTR(F.DOC_NO, 1, 4), '9980', 'PXC', 'PXR'), 'PXR'),
CASE
    WHEN F.FLIGHT_NO <8000 THEN 'VN'
    WHEN F.FLIGHT_NO >8999 THEN 'VN'
    ELSE '0V'
END
